# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcInspector < Formula
  desc "Browse your local Claude Code session history through a polished, private web UI."
  homepage "https://github.com/offbeatengineer/cc-inspector"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.4.0/cc-inspector_darwin_amd64.tar.gz"
      sha256 "3950819333e5eaf79ae1d4b66c810f549b0aa292d7017efe52b73bdd594d2992"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.4.0/cc-inspector_darwin_arm64.tar.gz"
      sha256 "4ae47161494629b752ec2ff9c777f21b2469bcbfd9b9df9d1282a8b650931111"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.4.0/cc-inspector_linux_amd64.tar.gz"
      sha256 "b3bf99f2dec3a3c3763dac44dfac0c7dc1c44dba4ce2244d6c6dff5660c4b1c1"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.4.0/cc-inspector_linux_arm64.tar.gz"
      sha256 "750b7b1b4dd6df96dba44861a92a7179abcdf31ea956e4f3e3478744a8ed4f25"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  test do
    system "#{bin}/cc-inspector", "--version"
  end
end
