# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcInspector < Formula
  desc "Browse your local Claude Code session history through a polished, private web UI."
  homepage "https://github.com/offbeatengineer/cc-inspector"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.3.1/cc-inspector_darwin_amd64.tar.gz"
      sha256 "e5fed4a7e3f2fa03983425fc5b98da5a28eda8181f06c94d8e5665c6ba31dde0"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.3.1/cc-inspector_darwin_arm64.tar.gz"
      sha256 "a75cf429599301b4d1cd835e79216c8b4ee9a3cafbc209a6d094bf602c719e87"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.3.1/cc-inspector_linux_amd64.tar.gz"
      sha256 "c071b8dccd6c9328cee417b127bf82625eaff27d7904b3a6e52d74be80d30877"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.3.1/cc-inspector_linux_arm64.tar.gz"
      sha256 "ce1f88f1f87de61f4053e9564b11dd8cf75f49e842f40ebecd350280d6c6721c"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  test do
    system "#{bin}/cc-inspector", "--version"
  end
end
