# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcInspector < Formula
  desc "Browse your local Claude Code session history through a polished, private web UI."
  homepage "https://github.com/offbeatengineer/cc-inspector"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.1.3/cc-inspector_darwin_amd64.tar.gz"
      sha256 "8db02fca331c66006cb960d4a12d206b486ccf00060e4ecb869f5fe198f1f3b0"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.1.3/cc-inspector_darwin_arm64.tar.gz"
      sha256 "992f78d22ba2ed20b4452b678e5c94ffa94a8113aa0f0cc873606a4cf177026e"

      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.1.3/cc-inspector_linux_amd64.tar.gz"
      sha256 "a239d63eb8c76734ad01d199bd554fb0bfdd9d68e15717a1a29820c77fe930b3"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/cc-inspector/releases/download/v0.1.3/cc-inspector_linux_arm64.tar.gz"
      sha256 "94267984895bcbd3224405ef1dc30820eda058dba2feca0ab6aa77d445752375"
      define_method(:install) do
        bin.install "cc-inspector"
      end
    end
  end

  test do
    system "#{bin}/cc-inspector", "--version"
  end
end
