# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gsuite < Formula
  desc "CLI for Google Workspace APIs (Gmail, Drive, Docs, Sheets, Calendar)"
  homepage "https://github.com/offbeatengineer/gsuite-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/offbeatengineer/gsuite-cli/releases/download/v0.1.0/gsuite_0.1.0_darwin_amd64.tar.gz"
      sha256 "c8fb6e65cdfddf4b7ef4ac67b2c93763a47eea854256b2603a1d171f01f430c6"

      def install
        bin.install "gsuite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/offbeatengineer/gsuite-cli/releases/download/v0.1.0/gsuite_0.1.0_darwin_arm64.tar.gz"
      sha256 "3fef6a514f6d903426a8be10add75693923d73a1d46b2b8123d0ddeaf5f17832"

      def install
        bin.install "gsuite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/gsuite-cli/releases/download/v0.1.0/gsuite_0.1.0_linux_amd64.tar.gz"
      sha256 "3fd41d8656b3424b2d876664768b46e2c19b1add3e221fbb9ad2dc1bbe2af081"
      def install
        bin.install "gsuite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/gsuite-cli/releases/download/v0.1.0/gsuite_0.1.0_linux_arm64.tar.gz"
      sha256 "e3e47e686a5f32b7dbf2decdb92e368af3f944d5aa3b33fd76c2ec252711c81a"
      def install
        bin.install "gsuite"
      end
    end
  end

  test do
    system "#{bin}/gsuite", "--help"
  end
end
