# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hnews < Formula
  desc "A minimalist, premium Hacker News client"
  homepage "https://github.com/offbeatengineer/hnews"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/offbeatengineer/hnews/releases/download/v0.1.0/hnews_darwin_amd64.tar.gz"
      sha256 "25d6c29793e41ed90f6a9ea330aa622198017be1f80a486b5a124894152a2037"

      define_method(:install) do
        bin.install "hnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/offbeatengineer/hnews/releases/download/v0.1.0/hnews_darwin_arm64.tar.gz"
      sha256 "851ec61dbf89ba33db26a981e31e4c726394eb68b2271114546579a1035be573"

      define_method(:install) do
        bin.install "hnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/hnews/releases/download/v0.1.0/hnews_linux_amd64.tar.gz"
      sha256 "d3a90487aa652fbe44473bf01976130ba3fbb38476daffe7f604548f8183fbf5"
      define_method(:install) do
        bin.install "hnews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/offbeatengineer/hnews/releases/download/v0.1.0/hnews_linux_arm64.tar.gz"
      sha256 "f87b21280c68c716b6f8002f8025f5d2860d485f9d25bd5a3f93f13140d20699"
      define_method(:install) do
        bin.install "hnews"
      end
    end
  end

  test do
    system "#{bin}/hnews", "--version"
  end
end
